name: test basico
on: [workflow_dispatch]

jobs:
  inicializa:
    runs-on: ubuntu-latest

    steps:
    - name: saludo
      run: echo "Hola Mundo"

    - name: test install python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: verifica la version
      run: python --version
